use [ademo]
CREATE TABLE Readers(
    ID NCHAR(8) PRIMARY KEY,
    UName NVARCHAR(20) NOT NULL,
    UPassword NVARCHAR(12),
    UEmail NVARCHAR(30) NOT NULL,
    CONSTRAINT CHK_REmail CHECK(UEmail LIKE '%@%')
)
CREATE TABLE Editors(
    ID NCHAR(8) PRIMARY KEY,
    EName NVARCHAR(20) NOT NULL,
    EEmail NVARCHAR(30) NOT NULL,
	EPassword NVARCHAR(12),
    CONSTRAINT CHK_EEmail CHECK(EEmail like '%@%')
)
CREATE TABLE Journalists(
    ID NCHAR(8) PRIMARY KEY,
    JName NVARCHAR(20) NOT NULL,
    JEmail NVARCHAR(30) NOT NULL,
	JPassword NVARCHAR(12),
    CONSTRAINT CHK_JEmail CHECK(JEmail like '%@%')
)
CREATE TABLE Topics(
    TopicID NCHAR(8) PRIMARY KEY,
    TopicName NVARCHAR(15) NOT NULL
)
CREATE TABLE Articles(
    AID NCHAR(8) PRIMARY KEY,
    Title NVARCHAR(MAX) NOT NULL,
    Content NVARCHAR(MAX) NOT NULL,
    PostDate DATE NOT NULL,
    AState INT NOT NULL,
    EID NCHAR(8),
    CONSTRAINT FK_EditorID FOREIGN KEY (EID) REFERENCES [dbo].[Editors](ID),
    TID NCHAR(8),
    CONSTRAINT FK_TopicID FOREIGN KEY (TID) REFERENCES [dbo].[Topics](TopicID),
    JID NCHAR(8),
    CONSTRAINT FK_JournalistID FOREIGN KEY (JID) REFERENCES [dbo].[Journalists](ID)
)
CREATE TABLE Manage(
    EID NCHAR(8),
    JID NCHAR(8),
    CONSTRAINT FK_MNEditorID FOREIGN KEY (EID) REFERENCES [dbo].[Editors](ID),
    CONSTRAINT FK_MNJournalistID FOREIGN KEY (JID) REFERENCES [dbo].[Journalists](ID)
)
CREATE TABLE UView(
    AID NCHAR(8),
    RID NCHAR(8),
    CONSTRAINT FK_UVArticleID FOREIGN KEY (AID) REFERENCES [dbo].[Articles](AID),
    CONSTRAINT FK_UVReaderID FOREIGN KEY (RID) REFERENCES [dbo].[Readers](ID)
)
